http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  emp:
    host: localhost
    path: 
      - '/api/employees'
      - '/api/employees/:id'
  auth:
    host: localhost
    path:
      - '/api/login'
  config:
    host: localhost
    path:
      - '/api/env/:env'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  empService:
    url: 'http://localhost:9000'
  authService:
    url: 'http://localhost:9001'
  configService:
    url: 'http://localhost:9002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  employeePipeline:
    apiEndpoints:
      - emp
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: "[header] ${req.headers.authorization}"
      - jwt:
          - action:
              secretOrPublicKey: 'secretKeyHere@123'
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: empService 
              changeOrigin: true
  authPipeline:
    apiEndpoints:
        - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService 
              changeOrigin: true
  configPipeline:
    apiEndpoints:
        - config
    policies:
      - proxy:
          - action:
              serviceEndpoint: configService 
              changeOrigin: true